server:
  port: 8084

spring:
  application:
    name: finance
  # 解决中文乱码问题
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dafuweng_finance?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        password: nacos
        username: nacos
        namespace: afae1f3f-8800-48c4-a161-c525a45538c9

mybatis-plus:
  mapper-locations: classpath:finance/mapper/*.xml
  type-aliases-package: com.dafuweng.finance.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.dafuweng: DEBUG
